Tests/trackscontroller audio
accentor/api pull request #126
Opened 2020-10-14 18:56 UTC by robbevp

fix #85

2020-10-14 19:14 UTC, robbevp commented
Fun bug I couldn't figure out: if tests working with `TranscodedItem` failed, I got empty files like `["deleniti",` or `["ut",` in the app root. Oh well 🤷

2020-11-01 13:24 UTC, charvp requested changes
Instead of installing ffmpeg, the call should be mocked.

2020-12-05 10:35 UTC, charvp approved these changes

2020-12-05 10:35 UTC, charvp commented on .github/workflows/ci.yml
> +          bundle exec rubocop -c .rubocop.yml
These changes seem unnecessary and have merge conflicts.

2020-12-05 11:24 UTC, charvp requested changes
Tests fail in CI

2020-12-05 11:51 UTC, charvp approved these changes

2020-12-05 11:51 UTC, merged